sudo: false
language: python

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy-5.3.1"

sudo: false
install:
  - "pip install -U pip setuptools"
  - "pip install ."
  - "pip install -r test_requirements.txt"
  - "pip install flake8"
  - "pip install sphinx"
before_script:
  - "flake8 --max-complexity 10 h2 test"
  - "sphinx-build -nW -b html -d docs/build/doctrees docs/source docs/build/html"
script:
  - ./.travis/run.sh
