language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - pypy

sudo: false
install:
  - "pip install -U pip setuptools"
  - "pip install ."
  - "pip install -r test_requirements.txt"
  - "pip install flake8"
before_script: "flake8 --max-complexity 10 h2 test"
script:
  - >
      if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
        py.test test/
      else
        py.test -n 4 --cov h2 test/
      fi
